---
version: '3.8'
services:
  api:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: jokester
    ports:
      - "1950:80"
    env_file:
      - ../.env
